### ISSUE TITLE
ERR_OSSL_EVP_UNSUPPORTED

### ISSUE THREAD

**Issue by hayoul** [develancer/topola-webpack#3]
There Is an issue when running it.

Run `npm audit` for details.
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/topola-webpack-master/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/topola-webpack-master/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/topola-webpack-master/node_modules/webpack/lib/NormalModule.js:471:10)
    at /topola-webpack-master/node_modules/webpack/lib/NormalModule.js:503:5
    at /topola-webpack-master/node_modules/webpack/lib/NormalModule.js:358:12
    at /topola-webpack-master/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/topola-webpack-master/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/topola-webpack-master/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/topola-webpack-master/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /topola-webpack-master/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /topola-webpack-master/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'

**Comment by hayoul** [comment]
which npm version are you using ? mine is Node.js v18.15.0

**Comment by hayoul** [comment]
I finally fixed it by adding export NODE_OPTIONS=--openssl-legacy-provider
 in the .sh.
